import type { Metadata } from "next";
import { betaStatus, loginUrl, pageMetadata, releaseNote, signupUrl } from "@/lib/site";

export const metadata: Metadata = pageMetadata("/about", "About | TeamShastra", "Learn about TeamShastra, a field service management software platform currently in public beta before production release.");

export default function AboutPage() {
  return (
    <main><section className="page-hero"><div className="section-inner"><span className="eyebrow">About</span><h1>TeamShastra helps service teams test field operations workflows with less friction.</h1><p className="page-lead">{betaStatus} {releaseNote} The public website explains the product while the application domain hosts beta signup, login, and test workspaces.</p><div className="hero-actions"><a className="button primary" href={signupUrl}>Join Beta</a><a className="button secondary" href={loginUrl}>Login</a></div></div></section><section className="section"><div className="section-inner split-grid"><div><h2>One brand, two clear surfaces.</h2><p className="section-copy">teamshastra.com is the public marketing website for SEO, product education, policy pages, and beta updates. app.teamshastra.com is the application platform for beta signup, login, company creation, and testing.</p></div><div className="card"><h3>Beta testing path</h3><ul className="list"><li>Visitor reads the marketing website.</li><li>Visitor clicks Join Beta.</li><li>Visitor lands on app.teamshastra.com/signup.</li><li>Visitor creates a test company and evaluates TeamShastra before production release.</li></ul></div></div></section><section className="section alt"><div className="section-inner banner"><div><h2>Help test TeamShastra before launch.</h2><p>{betaStatus} {releaseNote}</p></div><a className="button primary" href={signupUrl}>Join Beta</a></div></section></main>
  );
}